name: CD AUBase410

on:
  workflow_dispatch:
    inputs:
      bal_central_environment:
        description: Ballerina Central Environment
        type: choice
        options:
        - STAGE
        - DEV
        - PROD
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xmx4G
    steps:
      - uses: actions/checkout@v3

      - name: Ballerina Build AUBase410
        uses: ballerina-platform/ballerina-action@2201.5.0
        with:
          args:
            pack
        env:
          WORKING_DIR: ./aubase410
          JAVA_HOME: /usr/lib/jvm/default-jvm

      - name: Push to Staging AUBase410
        if: github.event.inputs.bal_central_environment == 'STAGE'
        uses: ballerina-platform/ballerina-action/@2201.5.0
        with:
          args:
            push
        env:
          WORKING_DIR: ./aubase410
          JAVA_HOME: /usr/lib/jvm/default-jvm
          BALLERINA_STAGE_CENTRAL: true
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}

      - name: Push to Dev AUBase410
        if: github.event.inputs.bal_central_environment == 'DEV'
        uses: ballerina-platform/ballerina-action/@2201.5.0
        with:
          args:
            push
        env:
          WORKING_DIR: ./aubase410
          JAVA_HOME: /usr/lib/jvm/default-jvm
          BALLERINA_DEV_CENTRAL: true
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}      

      - name: Push to Prod AUBase410
        if: github.event.inputs.bal_central_environment == 'PROD'
        uses: ballerina-platform/ballerina-action/@2201.5.0
        with:
          args:
            push
        env:
          WORKING_DIR: ./aubase410
          JAVA_HOME: /usr/lib/jvm/default-jvm
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_PROD_ACCESS_TOKEN }}
